version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "${KAFKA_VOLUME}:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "${KAFKA_VOLUME}:/bitnami/kafka"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ADVERTISED_HOST_NAME}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
