#!/bin/bash

#================================================================
# Copyright (c) 2021 Birch Framework
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#================================================================

SCRIPTS_DIR=$(dirname $(realpath ${0}))
PARENT_DIR=$(dirname ${SCRIPTS_DIR})

cd ${PARENT_DIR}

ARTIFACT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
[ $? -ne 0 ] && exit 2

VERSION=${ARTIFACT_VERSION}
read -e -p "New version: " -i ${VERSION} VERSION
[ $? -ne 0 ] && exit 3

if [ "${VERSION}" == "${ARTIFACT_VERSION}" ]; then
  echo "New version is the the same as current version; version will not be updated."
  exit 1
else
  mvn versions:set -q -DnewVersion=${VERSION} -DgenerateBackupPoms=false

  RELEASE_VERSION=$(echo ${VERSION} | cut -d'-' -f1)

  sed -e "s|<birch.version>.*</birch.version>|<birch.version>${VERSION}</birch.version>|g" birch-starter/pom.xml > birch-starter/pom.xml.new && \
  mv birch-starter/pom.xml.new birch-starter/pom.xml
  [ $? -ne 0 ] && exit 2

  sed -e "s|<version>.*</version>|<version>${RELEASE_VERSION}</version>|g" birch-starter/README.md > birch-starter/README.md.new && \
  mv birch-starter/README.md.new birch-starter/README.md
  [ $? -ne 0 ] && exit 3
fi
